### ISSUE TITLE
Make microservice user-configurable

### ISSUE THREAD

**Issue by mtbc** [ome/omero-ms-zarr#12]
`RequestHandlerForImage` appears at `image/` and defines constants like compressor, how many pixel buffers to cache, what chunk size to aim for, etc. The companion downloader script `fetch-ms-zarr` chooses between a grouped representation or not, whether to write chunks nested or flattened, etc. These could all be made user-configurable.

**Comment by mtbc** [comment]
Given #17 and #29 the only outstanding issue is,

> whether to write chunks nested or flattened

viz.

```python
        chunk_name_server = '.'.join(map(str, chunk))  # flat remotely
        chunk_name_client = '.'.join(map(str, chunk))  # flat locally
```
can take a `'/'` instead of a `'.'` so the CLI args could choose for each.

**Comment by joshmoore** [comment]
That'd be great. That's essentially how `n5-zarr` and zarr's upcoming `FSStore` do it as well.
