### ISSUE TITLE
include rendering information in metadata from microservice

### ISSUE THREAD

**Issue by mtbc** [ome/omero-ms-zarr#30]
Will need to bring the rendering bean up in the application context.

**Comment by mtbc** [comment]
Could be we simply need `internal-ome.api.IRenderingSettings` rather than the rendering bean, will see what this rendering metadata actually is.

**Comment by joshmoore** [comment]
@will-moore : can you point to the imgData loading code from webgateway and add any gotchas or caveats that you know about here?

**Comment by will-moore** [comment]
Sorry - https://github.com/ome/omero-web/blob/d8a68131ece0247b590e0be8c365817faefe47b6/omeroweb/webgateway/marshal.py#L91

**Comment by mtbc** [comment]
https://github.com/ome/omero-ms-zarr/blob/master/spec.md is now updated.
