### ISSUE TITLE
HCS Well metadata

### ISSUE THREAD

**Issue by will-moore** [ome/omero-ms-zarr#76]
Currently, we have Plate metadata like:

```
"plate": {
        "column_names": [
            1, 2, 3
        ],
        "columns": 3,
        "row_names": [
            "A", "B"
        ],
        "rows": 2
        "images": [
            {"path": "0/A/3/Field_1"},
            {"path": "0/B/2/Field_1"},
            {"path": "0/A/1/Field_1"},
            {"path": "0/B/3/Field_1"},
            {"path": "0/A/2/Field_1"},
            {"path": "0/B/1/Field_1"}
        ],
        "name": "plate1_1_013",
        "plateAcquisitions": [
            {"path": "0"}
        ],
    }
```

The presence of the `"plate":{}` in `url/.zattrs` is currently used by vizarr and napari to know that the URL is a plate.
For an image the `url/.zattrs` contains `"omero":{}` and `"multiscales":{}`.
For labels, the `url/.zattrs` contains `"labels": ["0", "1"]` list.
NB: Maybe this should be `"labels": [{"path": "0"}, {"path": "1"}]`

But, for a Well we don't have `url/.zattrs`, so we need something to identify a Well.
This could be:
```
"well": {
    "images": [
        {"path": "0/A/1/Field_1"}, {"path": "0/A/1/Field_2"},
    ],
}
```
But this is redundant with the `"images"` in the plate metadata.

Option 1
--------
Store "images" on Well - not on Plate

 - Pros:
    - When loading Well, we have direct access to children - consistent with e.g. multiscales, labels etc.
 - Cons:
    - When we are loading "Plate", we don't know max number of fields (do we need to?) - Propose to add `"fields": 2` to the `plate` metadata.
    - We also don't know which Wells are populated vv empty. This could be useful in sparsely-populated Plates. Don't want to try to load a large number of empty Wells. Maybe Plate should have `"wells": [{"path":"A/1"}, {"path":"A/2"}]`

Option 2
--------
Store "images" on Plate - not on Well

 - Pros:
    - We have ALL the images info when loading Plate - know e.g. number of fields for each Well.
 - Cons:
    - For big plates (e.g. idr0033) we have 384 wells x 9 Fields, so "images" list will be 3456 items long. Is that too long?
    - When loading a Well, we need to make an extra call to load child fields from the parent Plate.
    - Consistency: generally best if we stick to the rule that "containers should list their children". If we don't put this in `"well":{}` then we just have an empty dict!

cc @sbesson @joshmoore

**Comment by will-moore** [comment]
So, I think I prefer Option 2, but this also means that Plate should be updated with 'fields', and 'wells' instead of 'images':
```
"plate": {
        "column_names": [
            1, 2, 3
        ],
        "columns": 3,
        "row_names": [
            "A", "B"
        ],
        "rows": 2
        "wells": [
            {"path": "0/A/3"},
            {"path": "0/B/2"},
            {"path": "0/A/1"},
            {"path": "0/B/3"},
            {"path": "0/A/2"},
            {"path": "0/B/1"}
        ],
        "fields": 2,
        "name": "plate1_1_013",
        "plateAcquisitions": [
            {"path": "0"}
        ],
    }
```
Then Well has:
```
"well": {
    "images": [
        {"path": "Field_1"},
        {"path": "Field_2"}
    ]
}
```

Other issues:
 - This means that Plate has `"plate":{}` and a Well has `"well":{}` but an Image has `"omero":{}, "multiscales":{}`, so maybe that `omero` key should be renamed to `image`?
 - As mentioned above, labels should have 'path', e.g. `"labels": [{"path": "0"}, {"path": "1"}]`

**Comment by manics** [comment]
If `fields` is the maximum number of fields perhaps it'd be better to name it as such, e.g. `max_fields`? Otherwise the name implies all wells have that number of fields.

**Comment by joshmoore** [comment]
> maybe that omero key should be renamed to image?

If we either limit it further or go ahead and make sure we're happy supporting everything in there.

> NB: Maybe this should be "labels": [{"path": "0"}, {"path": "1"}]

I can see that, especially if we ever see it needing more metadata.

> So, I think I prefer Option 1,

Ditto

**Comment by will-moore** [comment]
@manics I think we imply that "all data may be sparse". We don't assert that all Wells exist, so if we have `"rows": 8, "columns": 12` this really means `"max_rows": 8, "max_columns": 12`, and it doesn't mean that every row has 12 columns. Although we would have the `"wells": []` info on the plate to check.

But, I have just thought of a bigger "con" to Option1: - We can't directly load an Image for each Well, since we don't know what the "path/to/image" is, unless we assume that the first field of a Well is `Field_1`. Maybe we should ensure that this naming is used?

**Comment by joshmoore** [comment]
> unless we assume that the first field of a Well is `Field_1`. Maybe we should ensure that this naming is used?

You mean all wells must use this naming? If we're specifying a location in the metadata where the path can be encoded, then I would try to avoid a hard-coding.

**Comment by will-moore** [comment]
Maybe we should remove the "Field_", or possibly, the Plate should list `"field_names": ["Field_1", "Field_2"]` as it does for "row_names", and "column_names"

**Comment by will-moore** [comment]
Jason mentioned: https://wellmap.readthedocs.io/en/latest/file_format.html which looks like a more compact way of storing the reagents, treatment etc of every well on a Plate. Instead of explicitly listing all attributes of each Well, it provides rules such as "All wells in column 1 have reagent X", or "alternative rows in column 1 have reagent Y" etc.

**Comment by sbesson** [comment]
Generally, same feeling as above i.e. I like option 1 or at least I would support explore it in the next iteration of the HCS work. Abstracting the `well` group as a collection of images has additionally some value outside the HCS spec e.g. I could imagine generally multi-position stage acquisitions re-using or extending this concept.

> If fields is the maximum number of fields perhaps it'd be better to name it as such, e.g. max_fields? 

I had a similar comment in https://github.com/ome/omero-ms-zarr/issues/73#issuecomment-717922871 about the naming of these concepts. I can certainly see `fields` being specified as an integer as long as we don't introduce the same concept further down e.g. at the `well` level and have `fields` refer to JSON objects.

>>     unless we assume that the first field of a Well is Field_1. Maybe we should ensure that this naming is used?
> You mean all wells must use this naming? If we're specifying a location in the metadata where the path can be encoded, then I would try to avoid a hard-coding.

Inspired to https://github.com/ome/omero-cli-zarr/pull/42, I would vote for having a dedicated `name`, rather than relying on a group name. At the level of the images, the `multiscale` specification include such a concept. A side-advantage of is that it might help addressing  the concerns of https://github.com/ome/omero-ms-zarr/issues/73#issuecomment-708225804, i.e. a standard `0/1/2...` naming scheme could be used.


Also, two additional comments:

- comparing with the OME schema, the maximum number of fields is a Plate Acquisition concept - see https://github.com/ome/omero-ms-zarr/issues/73#issuecomment-705627752. We might need to review that in a future iteration with a use case including multiple runs with varying numbers of fields of views per acquisition.
- `plateAcquisitions` and `wells` are effectively fairly redundant concepts as the former one can be inferred from the latter. I assume the main interest is a quick access to the list of runs i.e. some form of caching? Given the typical number of runs, it might be fairly inexpensive to do so but this might not necessarily be a MUST requirement.
- re `rows/columns/row_names/column_names`, one question I haven't been able to answer was: in the case of a very sparse plate `B3/B5/D2` is the number of rows/columns 3/3 or 4/5 i.e. does it reflect the minimum grid covering all wells or the minimum grid from A1 covering all wells?

**Comment by will-moore** [comment]
We should probably remove the `"rows": 8, "columns": 10,` and not mix integers and objects (always have objects under a key of the object type). We can remove the "row/column_names" and instead have:
```
"rows": ["A", "B"]
```
or even
```
"rows": [
  {"name": "A", "treatment": "control"},
  {"name": "B", "treatment": "drug 1"},
]
```
This is probably making it harder to get the row/col names and is not sufficient to specify all Well treatments, since row may have different treatments for different wells. But, it may still be useful if we want to specify any Well / Column metadata. Also, other lists are lists of objects (e.g. `{"path": "0"}`, so do we want this for rows/columns too, with just 'name' initially?

**Comment by joshmoore** [comment]
> always have objects under a key of the object type

I can see this. Certainly getting us closer to JSON-LD.

**Comment by will-moore** [comment]
OK, updating proposals:

```
"plate": {
        "columns": [
            {"name": "1"}, {"name": "2"}, {"name": "3"}
        ]
        "rows": [
            {"name": "A"}, {"name": "B"}
        ],
        "wells": [
            {"path": "0/A/3"},
            {"path": "0/B/2"},
            {"path": "0/A/1"},
            {"path": "0/B/3"},
            {"path": "0/A/2"},
            {"path": "0/B/1"}
        ],
        "fields": [
            {"name": "0"}, {"name": "1"}
        ],
        "name": "plate1_1_013",
        "acquisitions": [
            {"path": "0"}
        ],
    }
```
So, we have 'path' for wells and acquisitions (since this is a relative path within this container), but columns, rows and fields have 'name'.
I don't know what the default field names are if you do ```omero zarr export Plate:1``` since OMERO doesn't have field names, but we want to have field names on the plate so that we can go direct to the first image of any Well. E.g. "0/A/1/0/.zattrs" is an Image. Currently it uses "Field_1" etc.

Then, the 'path' of images in the well metadata must match the field names in the plate:
```
"well": {
    "images": [
        {"path": "0"},
        {"path": "1"}
    ]
}
```

**Comment by will-moore** [comment]
Summary of discussion:

 - plate layout mostly positive - rows and columns describes the physical plate - Wells is sparse list (@joshmoore suggested adding 'row' and 'column' to each well object).
 - Probably get rid of "fields" list of objects and have "field_count" (my preference) or "max_fields" instead. The only reason not to do this is if we later wanted to add metadata to each field at the plate level, e.g. coordinates etc.
 - Mostly I need the 'well' metadata to show Images in well (in vizarr or napari) and no changes were suggested here...
 - I'll go ahead and update omero-cli-zarr to write the spec above (except with "field_count" instead of "fields")
 - Also could add a `--no-pixels` or `--metadata-only` arg to omero-cli-zarr so that this can be used to update metadata on a previously-exported set of data (check what argument omero downloader uses for this).
 - Export a Plate of data for demo, and use this in the clients.

**Comment by will-moore** [comment]
https://github.com/ome/omero-cli-zarr/pull/43 addresses the proposed plate and well metadata changes.

But other issues above remain to be decided before next ome-zarr spec version:

- Plate has `"plate":{}` and a Well has `"well":{}` but an Image has `"omero":{}, "multiscales":{}`, so maybe that `omero` key should be renamed to `image` to be consistent?
- As mentioned above, labels should have an object with 'path', e.g. `"labels": [{"path": "0"}, {"path": "1"}] ` to be consistent.

Can move these to another issue if we want to close this one?

**Comment by will-moore** [comment]
Fixed in https://github.com/ome/omero-cli-zarr/pull/43
Other issues moved to https://github.com/ome/omero-ms-zarr/issues/77
